"""Install, uninstall, and run the prepare-commit-msg git hook."""

from __future__ import annotations

import os
import stat
from dataclasses import dataclass
from pathlib import Path

from .git_utils import git_dir, is_git_repo, staged_diff

HOOK_NAME = "prepare-commit-msg"

HOOK_MARKER = "# MIMO_COMMIT_GENIUS_HOOK_V1"

HOOK_TEMPLATE = """#!/usr/bin/env bash
{marker}
# Auto-generated by mimo-commit-genius. Safe to edit, but keep the marker line
# so `mimo-commit install-hook --uninstall` can recognize this file.

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"

# Skip when git already has a source (merge, squash, message provided via -m, etc.)
if [ -n "$COMMIT_SOURCE" ] && [ "$COMMIT_SOURCE" != "template" ]; then
    exit 0
fi

# If the user already wrote a message, do not overwrite it.
if [ -s "$COMMIT_MSG_FILE" ] && grep -qv '^#' "$COMMIT_MSG_FILE" 2>/dev/null | grep -q '[^[:space:]]'; then
    :
fi

if ! command -v {command} >/dev/null 2>&1; then
    echo "mimo-commit not found on PATH — install with: pip install mimo-commit-genius" >&2
    exit 0
fi

{command} suggest --write "$COMMIT_MSG_FILE" --quiet || true
"""


@dataclass
class HookInstallResult:
    hook_path: Path
    action: str  # "installed", "updated", "already-installed"


def hook_path(cwd: str | os.PathLike[str] | None = None) -> Path:
    return git_dir(cwd) / "hooks" / HOOK_NAME


def install_hook(
    cwd: str | os.PathLike[str] | None = None,
    *,
    command: str = "mimo-commit",
    force: bool = False,
) -> HookInstallResult:
    """Install (or reinstall) the prepare-commit-msg hook in the current repo."""
    if not is_git_repo(cwd):
        raise RuntimeError("Not inside a git repository")

    path = hook_path(cwd)
    path.parent.mkdir(parents=True, exist_ok=True)
    rendered = HOOK_TEMPLATE.format(marker=HOOK_MARKER, command=command)

    if path.exists():
        existing = path.read_text()
        if HOOK_MARKER in existing and not force:
            return HookInstallResult(hook_path=path, action="already-installed")
        if HOOK_MARKER not in existing and not force:
            raise RuntimeError(
                f"A non-mimo {HOOK_NAME} hook already exists at {path}. "
                "Re-run with --force to overwrite, or merge manually."
            )
        action = "updated"
    else:
        action = "installed"

    path.write_text(rendered)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return HookInstallResult(hook_path=path, action=action)


def uninstall_hook(cwd: str | os.PathLike[str] | None = None) -> bool:
    """Remove the hook if it was created by mimo-commit-genius."""
    path = hook_path(cwd)
    if not path.exists():
        return False
    content = path.read_text()
    if HOOK_MARKER not in content:
        raise RuntimeError(
            f"Refusing to remove {path}: it does not look like a mimo-commit hook."
        )
    path.unlink()
    return True


def staged_diff_for_hook(cwd: str | os.PathLike[str] | None = None) -> str:
    """Helper used by the CLI's --write mode to pull the diff during the hook."""
    return staged_diff(cwd)
